# -*- coding: utf-8 -*-
"""Titanic EDA .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdXfxYxiWuxeY5yjFYk_NhbetEUHXnkY
"""

# Titanic EDA Project


# Step 1: Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Load dataset (from seaborn's built-in Titanic dataset)
df = sns.load_dataset("titanic")

# Step 3: Basic Info
print("Shape of dataset:", df.shape)
print("\nMissing values:\n", df.isnull().sum())
print("\nFirst 5 rows:\n", df.head())

# Step 4: Univariate Analysis
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="sex")
plt.title("Gender Distribution")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="class")
plt.title("Passenger Class Distribution")
plt.show()

# Step 5: Survival Analysis
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="survived", hue="sex")
plt.title("Survival by Gender")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="survived", hue="class")
plt.title("Survival by Passenger Class")
plt.show()

# Step 6: Age Distribution
plt.figure(figsize=(6,4))
sns.histplot(df['age'].dropna(), kde=True, bins=30)
plt.title("Age Distribution")
plt.show()

# Step 7: Correlation Heatmap
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()